version: '2'

volumes:
  db_data: {}
  redis: {}
  gems: {}

services:
  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    command: redis-server --appendonly no --save ""
    image: redis:3.2-alpine
    volumes:
      - redis:/var/lib/redis/data

  web: &web
    image: civica-digital/urbem-bot:development
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
    environment:
      - DATABASE_HOST=db

  sidekiq:
    <<: *web
    command: bundle exec sidekiq
    depends_on:
      - redis
