version: '3'

volumes:
  db_data: {}
  redis: {}

services:
  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    command: redis-server --appendonly no --save ""
    image: redis:3.2-alpine
    volumes:
      - redis:/var/lib/redis/data

  web: &web
    image: civica-digital/quake-relief-cdmx:development
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=
      - DATABASE_USERNAME=postgres

  sidekiq:
    <<: *web
    command: bundle exec sidekiq
    depends_on:
      - redis
