FROM ruby:2.4.1-alpine

# Runtime
ENV APP_HOME=/usr/src/app \
    LANG=C.UTF-8 \
    PAGER='busybox less' \
    PATH=/usr/src/app/bin:$PATH \
    TERM='xterm-256color' \
    RAILS_ENV=development

WORKDIR $APP_HOME

EXPOSE 3000

CMD rm -f tmp/pids/server.pid && rails server -b 0.0.0.0

STOPSIGNAL SIGKILL

RUN set -ex \
    && apk update \
    && apk upgrade \
    && apk add --no-cache --virtual .runtime \
      tzdata \
      postgresql-dev \
      nodejs \
      bash

# Build
RUN set -ex \
    && apk add --no-cache --virtual .build \
      ruby-dev \
      build-base \
      git

# Gems
COPY Gemfile $APP_HOME/
RUN bundle install --jobs 4 --retry 3
